# Generated by Django 4.1.3 on 2023-01-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailuser', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
