# Generated by Django 4.1.3 on 2023-01-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myappstaff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_q', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.add_parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueDurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_q', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.add_durable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('reasonfromstaff', models.TextField(default='', max_length=500)),
                ('status', models.CharField(choices=[('รออนุมัติ', 'รออนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('รอยืนยันการรับ', 'รอยืนยันการรับ'), ('กำลังยืม', 'กำลังยืม'), ('รอยืนยันการคืน', 'รอยืนยันการคืน'), ('ยืมสำเร็จ', 'ยืมสำเร็จ'), ('คืนสำเร็จ', 'คืนสำเร็จ'), ('คืนไม่สำเร็จ', 'คืนไม่สำเร็จ')], default='รออนุมัติ', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('statusParcel', models.CharField(blank=True, default='', max_length=200)),
                ('nameposition', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='positon_parcel', to='myappstaff.settingposition')),
                ('parcel_item', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loan_parcels', to='myappstaff.add_parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('reasonfromstaff', models.TextField(default='', max_length=500)),
                ('status', models.CharField(choices=[('รออนุมัติ', 'รออนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('รอยืนยันการรับ', 'รอยืนยันการรับ'), ('กำลังยืม', 'กำลังยืม'), ('รอยืนยันการคืน', 'รอยืนยันการคืน'), ('ยืมสำเร็จ', 'ยืมสำเร็จ'), ('คืนสำเร็จ', 'คืนสำเร็จ'), ('คืนไม่สำเร็จ', 'คืนไม่สำเร็จ')], default='รออนุมัติ', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('statusDurable', models.CharField(blank=True, default='', max_length=200)),
                ('durable_item', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loan_durable', to='myappstaff.add_durable')),
                ('nameposition', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='positon_durable', to='myappstaff.settingposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListFromRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('brand', models.CharField(default='', max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('link', models.URLField(default='')),
                ('description', models.TextField(default='', max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('รออนุมัติ', 'รออนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('รอยืนยันการรับ', 'รอยืนยันการรับ'), ('กำลังยืม', 'กำลังยืม'), ('รอยืนยันการคืน', 'รอยืนยันการคืน'), ('ยืมสำเร็จ', 'ยืมสำเร็จ'), ('คืนสำเร็จ', 'คืนสำเร็จ'), ('คืนไม่สำเร็จ', 'คืนไม่สำเร็จ')], default='รออนุมัติ', max_length=200)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('statusParcel', models.CharField(blank=True, default='', max_length=200)),
                ('nameposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.settingposition')),
                ('parcel_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.add_parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartDurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('statusDurable', models.CharField(blank=True, default='', max_length=200)),
                ('durable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.add_durable')),
                ('nameposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappstaff.settingposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
